name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build DB Docker image
        run: docker build . --file Dockerfile --tag db-image:latest
        working-directory: ./code/mysql-preloaded

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/db-image
          docker tag db-image:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
