name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build DB Docker image
        run: docker build . --file Dockerfile --build-arg ROOT_PASS=${{ secrets.DB_ROOT_PASS }} --tag db-image:latest
        working-directory: ./code/mysql-preloaded

      
      - name: Build Node App Docker image
        run: docker build . --file Dockerfile --build-arg DB_USER=${{ secrets.DB_USER }} --build-arg DB_PASS=${{ secrets.DB_PASS }} --build-arg DB_HOST=dbinstance.akhilsworld.shop --tag node-app:latest
        working-directory: ./

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          DB_IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/db-image
          NODE_IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/node-app
          docker tag db-image:latest $DB_IMAGE_NAME:latest
          docker tag node-app:latest $NODE_IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
          docker push $NODE_IMAGE_NAME:latest
